### ISSUE TITLE
short_open_tag required

### ISSUE THREAD

**Issue by sdieunidou** [Gabyfle/gLoad#13]
Hello,

Short_open_tag need to be set to TRUE to run project, because of usage of <?= syntax.
Maybe need to check this param in index.php or better: stop using short syntax in templates and replace it by a templating engine like Twig :D

**Comment by Gabyfle** [comment]
**TWIG** has just been added for themes templating. I'll push a commit in the next days for admin dashboard support.

**Comment by Gabyfle** [comment]
Fixed in : https://github.com/Gabyfle/gLoad/commit/f9ae15c677a204bb0f4029222938a9041ff11ae0 and in https://github.com/Gabyfle/gLoad/commit/8658e7cf423bd6bf869eb001d5d7088b61e72fd4
